language: node_js

node_js:
  - '11.6.0'

services:
  - mongodb

env:
  global:
    - SERVER_PORT=8080
    - JET_KEY=weblistsecret
    - MONGO_PROTOCOL=mongodb
    - MONGO_HOSTNAME=localhost:27017
    - MONGO_DB=liskit-test
    - SERVER_PROTOCOL=http
    - SERVER_HOSTNAME=localhost
